#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the latest Node Argon version and outputs it.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
ARGON_VERSION=$1;
if [[ ${ARGON_VERSION} = ""]]; then ARGON_VERSION='v4.8.4'; fi;

## constants
KEY='ARGON_VERSION'
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";
LATEST_URL="https://nodejs.org/download/release/latest-v4.x/";

## processing
__exists=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then
  ARGON_VERSION=$(cat ${CONF_FILE_PATH});
else
  ARGON_VERSION="v$(curl -sSlf ${LATEST_URL} | grep '>node-v' | tail -n 1 | cut -f 2 -d "\"" | cut -f 2 -d "v" | cut -f 1,2,3 -d ".")";
  if [[ $? != "0" ]]; then
    ${CURR_DIR}/utils/error "${KEY} could not be retrieved. Error accessing ${LATEST_URL}.";
    exit 1;
  fi;
fi;

## output
printf "${ARGON_VERSION}" > "${OUTPUT_FILE}" | cat;
