#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the latest Node Boron version and outputs it.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
BORON_VERSION=$1;
if [[ ${BORON_VERSION} = "" ]]; then BORON_VERSION='v6.11.3'; fi;

## constants
KEY='BORON_VERSION'
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";
LATEST_URL="https://nodejs.org/download/release/latest-v6.x/";

## processing
_=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then
  BORON_VERSION=$(cat ${CONF_FILE_PATH});
else
  BORON_VERSION="v$(curl -sSlf ${LATEST_URL} | grep '>node-v' | tail -n 1 | cut -f 2 -d "\"" | cut -f 2 -d "v" | cut -f 1,2,3 -d ".")";
  if [[ $? != "0" ]]; then
    ${CURR_DIR}/utils/error "${KEY} could not be retrieved. Error accessing ${LATEST_URL}.";
    exit 1;
  fi;
fi;

## output
printf "${BORON_VERSION}" > "${OUTPUT_FILE}";
printf "${BORON_VERSION}";
