#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the next semver tagging we should be using.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## constants
KEY='BUILD_VERSION';
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
BUILD_VERSION=$(${CURR_DIR}/../versioning/get-next -i -q);

## output
printf "${BUILD_VERSION}" > "${OUTPUT_FILE}" | cat;
