#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the API version of Docker we should be using. Defaults to v1.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
DOCKER_API_VERSION=$1;
if [[ ${DOCKER_API_VERSION} = "" ]]; then DOCKER_API_VERSION='v1'; fi;

## constants
KEY='DOCKER_API_VERSION';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
__exists=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then DOCKER_API_VERSION=$(cat "${CONF_FILE_PATH}"); fi;

## output
printf "${DOCKER_API_VERSION}" > "${OUTPUT_FILE}" | cat;
