#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the Hub URL for Docker. This is used for authentication.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## constants
KEY='DOCKER_HUB_URL';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";
DOCKER_HUB_URL='https://hub.docker.com';

## processing
_=$(stat "${CONF_FILE_PATH}" &>/dev/null);
if [[ $? = "0" ]]; then DOCKER_HUB_URL=$(cat "${CONF_FILE_PATH}"); fi;

## output
printf "${DOCKER_HUB_URL}" > "${OUTPUT_FILE}" | cat;
