#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the Docker registry URL we wish to push the image to. It 
# defaults to using the v1 address for Docker Hub if no configuration is specified.
#
# Usage:
#   docker_registry_url <api_version> <use_default>
#     api_version : {v1, v2}
#     use_default : {official, true} : optional, defaults to false
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
DOCKER_API_VERSION=$1;
if [[ ${DOCKER_API_VERSION} = '' ]]; then
  DOCKER_API_VERSION="$(${CURR_DIR}/docker_api_version)";
fi;

USE_OFFICIAL_DOCKER_HUB=$2;
if [[ ${USE_OFFICIAL_DOCKER_HUB} != 'true' ]] \
  && [[ ${USE_OFFICIAL_DOCKER_HUB} != 'official' ]]; then
  USE_OFFICIAL_DOCKER_HUB='false';
fi;

## constants
KEY='DOCKER_REGISTRY_URL';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
_=$(stat "${CONF_FILE_PATH}" &>/dev/null);
if [[ $? = "0" ]]; then
  DOCKER_REGISTRY_URL=$(cat "${CONF_FILE_PATH}");
elif [[ ${USE_OFFICIAL_DOCKER_HUB} = 'false' ]]; then
  DOCKER_REGISTRY_URL='';
elif [[ ${DOCKER_API_VERSION} = 'v2' ]]; then
  DOCKER_REGISTRY_URL='https://registry.hub.docker.com';
else
  DOCKER_REGISTRY_URL='https://index.docker.io';
fi;

## output
printf "${DOCKER_REGISTRY_URL}" > "${OUTPUT_FILE}";
printf "${DOCKER_REGISTRY_URL}";
