#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the Docker registry URL we wish to push the image to. It 
# defaults to using the v1 address for Docker Hub if no configuration is specified.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
DOCKER_API_VERSION=$1;
if [[ ${DOCKER_API_VERSION} = "" ]]; then
  DOCKER_API_VERSION="$(${CURR_DIR}/docker_api_version)";
fi;

## constants
KEY='DOCKER_REGISTRY_URL';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
_=$(stat "${CONF_FILE_PATH}" &>/dev/null);
if [[ $? = "0" ]]; then
  DOCKER_REGISTRY_URL=$(cat "${CONF_FILE_PATH}");
elif [[ ${DOCKER_API_VERSION} = 'v2' ]]; then
  DOCKER_REGISTRY_URL='https://registry.hub.docker.com';
else
  DOCKER_REGISTRY_URL='https://index.docker.io';
fi;

## output
printf "${DOCKER_REGISTRY_URL}" > "${OUTPUT_FILE}" | cat;
