#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the latest Gitbook release version number.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
GITBOOK_VERSION=$1;

## constants
KEY='GITBOOK_VERSION';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
_=$(stat "${CONF_FILE_PATH}" &>/dev/null);
if [[ $? = "0" ]]; then
  GITBOOK_VERSION=$(cat "${CONF_FILE_PATH}");
else
  npm install -g gitbook-cli &>/dev/null;
  if [[ $? != "0" ]]; then exit 1; fi;
  GITBOOK_VERSIONS=$(gitbook ls-remote | sed -e "s|, |  |g" | xargs -n1 echo | sort | egrep "^[0-9]\.[0-9]\.[0-9]$");
  if [[ $? = "0" ]]; then
    GITBOOK_VERSION=$(printf "${GITBOOK_VERSIONS}" | tail -n 1);
  else
    ${CURR_DIR}/utils/error "${KEY} could not be retrieved using gitbook-cli's 'gitbook ls-remote' command.";
    exit 1;
  fi;
fi;

## output
printf "${GITBOOK_VERSION}" > "${OUTPUT_FILE}" | cat;
