#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the repository name which we should push to.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
REPOSITORY_NAME=$1;
if [[ ${REPOSITORY_NAME} = ""]]; then
  ${CURR_DIR}/utils/error "A default REPOSITORY_NAME is required. Specify it as the first argument.";
  exit 1;
fi;

## constants
KEY='REPOSITORY_NAME';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
__exists=$(stat "${CONF_FILE_PATH}" &>/dev/null);
if [[ $? = "0" ]]; then REPOSITORY_NAME=$(cat "${CONF_FILE_PATH}"); fi;

## output
printf "${REPOSITORY_NAME}" > "${OUTPUT_FILE}" | cat;
