#!/bin/bash
#-------------------------------------------------------------------------------------
# This script retrieves the latest Yarn version and outputs it.
#-------------------------------------------------------------------------------------

## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;
${CURR_DIR}/utils/directories_exist;
if [[ $? != '0' ]]; then exit 1; fi;

## arguments
YARN_VERSION=$1;

## constants
KEY='YARN_VERSION';
CONF_FILE_PATH="${CONF_DIR}/${KEY}";
LATEST_URL="https://yarnpkg.com/latest.tar.gz";
OUTPUT_FILE="${SETUP_DIR}/${KEY}";

## processing
_=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then
  YARN_VERSION=$(cat ${CONF_FILE_PATH});
else
  YARN_VERSION="$(curl -sSlf ${LATEST_URL} | cut -f 8 -d "/")";
  if [[ $? != "0" ]]; then
    ${CURR_DIR}/utils/error "${KEY} could not be retrieved. Error accessing ${LATEST_URL}.";
    exit 1;
  fi;
fi;

## output
printf "${YARN_VERSION}" > "${OUTPUT_FILE}";
printf "${YARN_VERSION}";
